// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDWQclApX_hbGAqEgLPQ2Dffb6MiZV_SU',
    appId: '1:221579606629:web:54846ff70c00102d78248c',
    messagingSenderId: '221579606629',
    projectId: 'newproject-39511',
    authDomain: 'newproject-39511.firebaseapp.com',
    databaseURL: 'https://newproject-39511-default-rtdb.firebaseio.com',
    storageBucket: 'newproject-39511.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABqZnp1eDnE77_UzULh61vkOYnHmS63X4',
    appId: '1:221579606629:android:4cbb3d8168a36bd078248c',
    messagingSenderId: '221579606629',
    projectId: 'newproject-39511',
    databaseURL: 'https://newproject-39511-default-rtdb.firebaseio.com',
    storageBucket: 'newproject-39511.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6n_myheXxlwvonZoCocMBKgbST2I9kfc',
    appId: '1:221579606629:ios:58ffe43c5241184178248c',
    messagingSenderId: '221579606629',
    projectId: 'newproject-39511',
    databaseURL: 'https://newproject-39511-default-rtdb.firebaseio.com',
    storageBucket: 'newproject-39511.appspot.com',
    iosBundleId: 'com.example.abuSandia',
  );
}
